# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-Monitor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.monitorGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.monitorGroupBox.setEnabled(True)
        self.monitorGroupBox.setGeometry(QtCore.QRect(10, 10, 680, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox.setSizePolicy(sizePolicy)
        self.monitorGroupBox.setMinimumSize(QtCore.QSize(680, 100))
        self.monitorGroupBox.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitorGroupBox.setFont(font)
        self.monitorGroupBox.setObjectName("monitorGroupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.monitorGroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 661, 72))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_T1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_T1.setObjectName("verticalLayout_T1")
        self.typeTittleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeTittleLabel.sizePolicy().hasHeightForWidth())
        self.typeTittleLabel.setSizePolicy(sizePolicy)
        self.typeTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeTittleLabel.setFont(font)
        self.typeTittleLabel.setObjectName("typeTittleLabel")
        self.verticalLayout_T1.addWidget(self.typeTittleLabel)
        self.intervalTittleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalTittleLabel.sizePolicy().hasHeightForWidth())
        self.intervalTittleLabel.setSizePolicy(sizePolicy)
        self.intervalTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.intervalTittleLabel.setFont(font)
        self.intervalTittleLabel.setObjectName("intervalTittleLabel")
        self.verticalLayout_T1.addWidget(self.intervalTittleLabel)
        self.urlTittleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlTittleLabel.sizePolicy().hasHeightForWidth())
        self.urlTittleLabel.setSizePolicy(sizePolicy)
        self.urlTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urlTittleLabel.setFont(font)
        self.urlTittleLabel.setObjectName("urlTittleLabel")
        self.verticalLayout_T1.addWidget(self.urlTittleLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_T1)
        self.verticalLayout_R1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_R1.setObjectName("verticalLayout_R1")
        self.intervalLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel.sizePolicy().hasHeightForWidth())
        self.intervalLabel.setSizePolicy(sizePolicy)
        self.intervalLabel.setMaximumSize(QtCore.QSize(100, 20))
        self.intervalLabel.setObjectName("intervalLabel")
        self.verticalLayout_R1.addWidget(self.intervalLabel)
        self.typeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setMaximumSize(QtCore.QSize(100, 20))
        self.typeLabel.setObjectName("typeLabel")
        self.verticalLayout_R1.addWidget(self.typeLabel)
        self.urlLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel.sizePolicy().hasHeightForWidth())
        self.urlLabel.setSizePolicy(sizePolicy)
        self.urlLabel.setMaximumSize(QtCore.QSize(200, 20))
        self.urlLabel.setObjectName("urlLabel")
        self.verticalLayout_R1.addWidget(self.urlLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_R1)
        self.verticalLayout_T2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_T2.setObjectName("verticalLayout_T2")
        self.testTittleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTittleLabel.sizePolicy().hasHeightForWidth())
        self.testTittleLabel.setSizePolicy(sizePolicy)
        self.testTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testTittleLabel.setFont(font)
        self.testTittleLabel.setObjectName("testTittleLabel")
        self.verticalLayout_T2.addWidget(self.testTittleLabel)
        self.resultTittleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTittleLabel.sizePolicy().hasHeightForWidth())
        self.resultTittleLabel.setSizePolicy(sizePolicy)
        self.resultTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTittleLabel.setFont(font)
        self.resultTittleLabel.setObjectName("resultTittleLabel")
        self.verticalLayout_T2.addWidget(self.resultTittleLabel)
        self.notesTittleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTittleLabel.sizePolicy().hasHeightForWidth())
        self.notesTittleLabel.setSizePolicy(sizePolicy)
        self.notesTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notesTittleLabel.setFont(font)
        self.notesTittleLabel.setObjectName("notesTittleLabel")
        self.verticalLayout_T2.addWidget(self.notesTittleLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_T2)
        self.verticalLayout_R2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_R2.setObjectName("verticalLayout_R2")
        self.notesLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel.sizePolicy().hasHeightForWidth())
        self.notesLabel.setSizePolicy(sizePolicy)
        self.notesLabel.setMaximumSize(QtCore.QSize(150, 20))
        self.notesLabel.setObjectName("notesLabel")
        self.verticalLayout_R2.addWidget(self.notesLabel)
        self.resultLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultLabel.sizePolicy().hasHeightForWidth())
        self.resultLabel.setSizePolicy(sizePolicy)
        self.resultLabel.setMaximumSize(QtCore.QSize(150, 20))
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout_R2.addWidget(self.resultLabel)
        self.testTimeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLabel.sizePolicy().hasHeightForWidth())
        self.testTimeLabel.setSizePolicy(sizePolicy)
        self.testTimeLabel.setMaximumSize(QtCore.QSize(150, 20))
        self.testTimeLabel.setObjectName("testTimeLabel")
        self.verticalLayout_R2.addWidget(self.testTimeLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_R2)
        self.verticalLayout_Icon = QtWidgets.QVBoxLayout()
        self.verticalLayout_Icon.setObjectName("verticalLayout_Icon")
        self.iconLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel.sizePolicy().hasHeightForWidth())
        self.iconLabel.setSizePolicy(sizePolicy)
        self.iconLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.iconLabel.setAutoFillBackground(False)
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout_Icon.addWidget(self.iconLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_Icon)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.monitorGroupBox.setTitle(_translate("MainWindow", "Monitor"))
        self.typeTittleLabel.setText(_translate("MainWindow", "Type:"))
        self.intervalTittleLabel.setText(_translate("MainWindow", "Interval:"))
        self.urlTittleLabel.setText(_translate("MainWindow", "URL/Host:"))
        self.intervalLabel.setText(_translate("MainWindow", "5s"))
        self.typeLabel.setText(_translate("MainWindow", "SERVER"))
        self.urlLabel.setText(_translate("MainWindow", "www.google.com"))
        self.testTittleLabel.setText(_translate("MainWindow", "Test Time:"))
        self.resultTittleLabel.setText(_translate("MainWindow", "Result:"))
        self.notesTittleLabel.setText(_translate("MainWindow", "Notes:"))
        self.notesLabel.setText(_translate("MainWindow", "..."))
        self.resultLabel.setText(_translate("MainWindow", "SERVER"))
        self.testTimeLabel.setText(_translate("MainWindow", "2023-04-01 00:00:00"))

