# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(720, 600))
        MainWindow.setMaximumSize(QtCore.QSize(720, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.localTimeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.localTimeGroupBox.setGeometry(QtCore.QRect(10, 10, 340, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTimeGroupBox.sizePolicy().hasHeightForWidth())
        self.localTimeGroupBox.setSizePolicy(sizePolicy)
        self.localTimeGroupBox.setMaximumSize(QtCore.QSize(340, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.localTimeGroupBox.setFont(font)
        self.localTimeGroupBox.setObjectName("localTimeGroupBox")
        self.localTimeLabel = QtWidgets.QLabel(self.localTimeGroupBox)
        self.localTimeLabel.setGeometry(QtCore.QRect(10, 25, 320, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTimeLabel.sizePolicy().hasHeightForWidth())
        self.localTimeLabel.setSizePolicy(sizePolicy)
        self.localTimeLabel.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.localTimeLabel.setFont(font)
        self.localTimeLabel.setObjectName("localTimeLabel")





        self.utcTimeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.utcTimeGroupBox.setGeometry(QtCore.QRect(370, 10, 340, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.utcTimeGroupBox.sizePolicy().hasHeightForWidth())
        self.utcTimeGroupBox.setSizePolicy(sizePolicy)
        self.utcTimeGroupBox.setMaximumSize(QtCore.QSize(340, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.utcTimeGroupBox.setFont(font)
        self.utcTimeGroupBox.setObjectName("utcTimeGroupBox")
        self.utcTimeLabel = QtWidgets.QLabel(self.utcTimeGroupBox)
        self.utcTimeLabel.setGeometry(QtCore.QRect(10, 25, 320, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.utcTimeLabel.sizePolicy().hasHeightForWidth())
        self.utcTimeLabel.setSizePolicy(sizePolicy)
        self.utcTimeLabel.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.utcTimeLabel.setFont(font)
        self.utcTimeLabel.setObjectName("utcTimeLabel")



        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 90, 700, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(700, 450))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 690, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(690, 450))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(690, 900))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setMaximumSize(QtCore.QSize(720, 30))
        self.menubar.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setGeometry(QtCore.QRect(1016, 145, 120, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuFile.sizePolicy().hasHeightForWidth())
        self.menuFile.setSizePolicy(sizePolicy)
        self.menuFile.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setGeometry(QtCore.QRect(627, 351, 120, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuHelp.sizePolicy().hasHeightForWidth())
        self.menuHelp.setSizePolicy(sizePolicy)
        self.menuHelp.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTime_Zone = QtWidgets.QAction(MainWindow)
        self.actionTime_Zone.setObjectName("actionTime_Zone")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.menuEdit.addAction(self.actionTime_Zone)
        self.menuEdit.addAction(self.actionConfig)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.localTimeGroupBox.setTitle(_translate("MainWindow", "本地时间 Local Time"))
        self.localTimeLabel.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.utcTimeGroupBox.setTitle(_translate("MainWindow", "UTC 时间 UTC Time"))
        self.utcTimeLabel.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionTime_Zone.setText(_translate("MainWindow", "Time Zone"))
        self.actionConfig.setText(_translate("MainWindow", "Settings"))

    def addMonitorGroup(self, num):
        monitorGroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        monitorGroupBox.setEnabled(True)
        monitorGroupBox.setGeometry(QtCore.QRect(10, 10, 680, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(monitorGroupBox.sizePolicy().hasHeightForWidth())
        monitorGroupBox.setSizePolicy(sizePolicy)
        monitorGroupBox.setMinimumSize(QtCore.QSize(680, 100))
        monitorGroupBox.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        monitorGroupBox.setFont(font)
        monitorGroupBox.setObjectName("monitorGroupBox")
        horizontalLayoutWidget = QtWidgets.QWidget(monitorGroupBox)
        horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 661, 72))
        horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        horizontalLayout = QtWidgets.QHBoxLayout(horizontalLayoutWidget)
        horizontalLayout.setContentsMargins(0, 0, 0, 0)
        horizontalLayout.setObjectName("horizontalLayout")
        verticalLayout_T1 = QtWidgets.QVBoxLayout()
        verticalLayout_T1.setObjectName("verticalLayout_T1")
        typeTittleLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(typeTittleLabel.sizePolicy().hasHeightForWidth())
        typeTittleLabel.setSizePolicy(sizePolicy)
        typeTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        typeTittleLabel.setFont(font)
        typeTittleLabel.setObjectName("typeTittleLabel")
        verticalLayout_T1.addWidget(typeTittleLabel)
        intervalTittleLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(intervalTittleLabel.sizePolicy().hasHeightForWidth())
        intervalTittleLabel.setSizePolicy(sizePolicy)
        intervalTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        intervalTittleLabel.setFont(font)
        intervalTittleLabel.setObjectName("intervalTittleLabel")
        verticalLayout_T1.addWidget(intervalTittleLabel)
        urlTittleLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(urlTittleLabel.sizePolicy().hasHeightForWidth())
        urlTittleLabel.setSizePolicy(sizePolicy)
        urlTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        urlTittleLabel.setFont(font)
        urlTittleLabel.setObjectName("urlTittleLabel")
        verticalLayout_T1.addWidget(urlTittleLabel)
        horizontalLayout.addLayout(verticalLayout_T1)
        verticalLayout_R1 = QtWidgets.QVBoxLayout()
        verticalLayout_R1.setObjectName("verticalLayout_R1")
        intervalLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(intervalLabel.sizePolicy().hasHeightForWidth())
        intervalLabel.setSizePolicy(sizePolicy)
        intervalLabel.setMaximumSize(QtCore.QSize(100, 20))
        intervalLabel.setObjectName("intervalLabel")
        verticalLayout_R1.addWidget(intervalLabel)
        typeLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(typeLabel.sizePolicy().hasHeightForWidth())
        typeLabel.setSizePolicy(sizePolicy)
        typeLabel.setMaximumSize(QtCore.QSize(100, 20))
        typeLabel.setObjectName("typeLabel")
        verticalLayout_R1.addWidget(typeLabel)
        urlLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(urlLabel.sizePolicy().hasHeightForWidth())
        urlLabel.setSizePolicy(sizePolicy)
        urlLabel.setMaximumSize(QtCore.QSize(200, 20))
        urlLabel.setObjectName("urlLabel")
        verticalLayout_R1.addWidget(urlLabel)
        horizontalLayout.addLayout(verticalLayout_R1)
        verticalLayout_T2 = QtWidgets.QVBoxLayout()
        verticalLayout_T2.setObjectName("verticalLayout_T2")
        testTittleLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(testTittleLabel.sizePolicy().hasHeightForWidth())
        testTittleLabel.setSizePolicy(sizePolicy)
        testTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        testTittleLabel.setFont(font)
        testTittleLabel.setObjectName("testTittleLabel")
        verticalLayout_T2.addWidget(testTittleLabel)
        resultTittleLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(resultTittleLabel.sizePolicy().hasHeightForWidth())
        resultTittleLabel.setSizePolicy(sizePolicy)
        resultTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        resultTittleLabel.setFont(font)
        resultTittleLabel.setObjectName("resultTittleLabel")
        verticalLayout_T2.addWidget(resultTittleLabel)
        notesTittleLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(notesTittleLabel.sizePolicy().hasHeightForWidth())
        notesTittleLabel.setSizePolicy(sizePolicy)
        notesTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        notesTittleLabel.setFont(font)
        notesTittleLabel.setObjectName("notesTittleLabel")
        verticalLayout_T2.addWidget(notesTittleLabel)
        horizontalLayout.addLayout(verticalLayout_T2)
        verticalLayout_R2 = QtWidgets.QVBoxLayout()
        verticalLayout_R2.setObjectName("verticalLayout_R2")
        notesLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(notesLabel.sizePolicy().hasHeightForWidth())
        notesLabel.setSizePolicy(sizePolicy)
        notesLabel.setMaximumSize(QtCore.QSize(150, 20))
        notesLabel.setObjectName("notesLabel")
        verticalLayout_R2.addWidget(notesLabel)
        resultLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(resultLabel.sizePolicy().hasHeightForWidth())
        resultLabel.setSizePolicy(sizePolicy)
        resultLabel.setMaximumSize(QtCore.QSize(150, 20))
        resultLabel.setObjectName("resultLabel")
        verticalLayout_R2.addWidget(resultLabel)
        testTimeLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(testTimeLabel.sizePolicy().hasHeightForWidth())
        testTimeLabel.setSizePolicy(sizePolicy)
        testTimeLabel.setMaximumSize(QtCore.QSize(150, 20))
        testTimeLabel.setObjectName("testTimeLabel")
        verticalLayout_R2.addWidget(testTimeLabel)
        horizontalLayout.addLayout(verticalLayout_R2)
        verticalLayout_Icon = QtWidgets.QVBoxLayout()
        verticalLayout_Icon.setObjectName("verticalLayout_Icon")
        iconLabel = QtWidgets.QLabel(horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(iconLabel.sizePolicy().hasHeightForWidth())
        iconLabel.setSizePolicy(sizePolicy)
        iconLabel.setMaximumSize(QtCore.QSize(60, 60))
        iconLabel.setAutoFillBackground(False)
        iconLabel.setText("")
        iconLabel.setObjectName("iconLabel")
        verticalLayout_Icon.addWidget(iconLabel)
        horizontalLayout.addLayout(verticalLayout_Icon)

