# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_v1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(720, 600))
        MainWindow.setMaximumSize(QtCore.QSize(720, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.localTimeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.localTimeGroupBox.setGeometry(QtCore.QRect(10, 10, 340, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTimeGroupBox.sizePolicy().hasHeightForWidth())
        self.localTimeGroupBox.setSizePolicy(sizePolicy)
        self.localTimeGroupBox.setMaximumSize(QtCore.QSize(340, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.localTimeGroupBox.setFont(font)
        self.localTimeGroupBox.setObjectName("localTimeGroupBox")
        self.localTimeLabel = QtWidgets.QLabel(self.localTimeGroupBox)
        self.localTimeLabel.setGeometry(QtCore.QRect(10, 25, 320, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localTimeLabel.sizePolicy().hasHeightForWidth())
        self.localTimeLabel.setSizePolicy(sizePolicy)
        self.localTimeLabel.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.localTimeLabel.setFont(font)
        self.localTimeLabel.setObjectName("localTimeLabel")
        self.utcTimeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.utcTimeGroupBox.setGeometry(QtCore.QRect(370, 10, 340, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.utcTimeGroupBox.sizePolicy().hasHeightForWidth())
        self.utcTimeGroupBox.setSizePolicy(sizePolicy)
        self.utcTimeGroupBox.setMaximumSize(QtCore.QSize(340, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.utcTimeGroupBox.setFont(font)
        self.utcTimeGroupBox.setObjectName("utcTimeGroupBox")
        self.utcTimeLabel = QtWidgets.QLabel(self.utcTimeGroupBox)
        self.utcTimeLabel.setGeometry(QtCore.QRect(10, 25, 320, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.utcTimeLabel.sizePolicy().hasHeightForWidth())
        self.utcTimeLabel.setSizePolicy(sizePolicy)
        self.utcTimeLabel.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.utcTimeLabel.setFont(font)
        self.utcTimeLabel.setObjectName("utcTimeLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 130, 700, 420))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(700, 440))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 418))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(698, 418))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 418))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 682, 566))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.monitorGroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.monitorGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox.setSizePolicy(sizePolicy)
        self.monitorGroupBox.setMinimumSize(QtCore.QSize(680, 100))
        self.monitorGroupBox.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitorGroupBox.setFont(font)
        self.monitorGroupBox.setObjectName("monitorGroupBox")
        self.typeLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.typeLabel.setGeometry(QtCore.QRect(100, 30, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setMaximumSize(QtCore.QSize(100, 20))
        self.typeLabel.setObjectName("typeLabel")
        self.intervalLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.intervalLabel.setGeometry(QtCore.QRect(100, 50, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel.sizePolicy().hasHeightForWidth())
        self.intervalLabel.setSizePolicy(sizePolicy)
        self.intervalLabel.setMaximumSize(QtCore.QSize(100, 20))
        self.intervalLabel.setObjectName("intervalLabel")
        self.urlLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.urlLabel.setGeometry(QtCore.QRect(100, 70, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel.sizePolicy().hasHeightForWidth())
        self.urlLabel.setSizePolicy(sizePolicy)
        self.urlLabel.setMaximumSize(QtCore.QSize(200, 20))
        self.urlLabel.setObjectName("urlLabel")
        self.typeTittleLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.typeTittleLabel.setGeometry(QtCore.QRect(20, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeTittleLabel.sizePolicy().hasHeightForWidth())
        self.typeTittleLabel.setSizePolicy(sizePolicy)
        self.typeTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeTittleLabel.setFont(font)
        self.typeTittleLabel.setObjectName("typeTittleLabel")
        self.intervalTittleLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.intervalTittleLabel.setGeometry(QtCore.QRect(20, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalTittleLabel.sizePolicy().hasHeightForWidth())
        self.intervalTittleLabel.setSizePolicy(sizePolicy)
        self.intervalTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.intervalTittleLabel.setFont(font)
        self.intervalTittleLabel.setObjectName("intervalTittleLabel")
        self.urlTittleLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.urlTittleLabel.setGeometry(QtCore.QRect(20, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlTittleLabel.sizePolicy().hasHeightForWidth())
        self.urlTittleLabel.setSizePolicy(sizePolicy)
        self.urlTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urlTittleLabel.setFont(font)
        self.urlTittleLabel.setObjectName("urlTittleLabel")
        self.resultLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.resultLabel.setGeometry(QtCore.QRect(380, 50, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultLabel.sizePolicy().hasHeightForWidth())
        self.resultLabel.setSizePolicy(sizePolicy)
        self.resultLabel.setMaximumSize(QtCore.QSize(150, 20))
        self.resultLabel.setObjectName("resultLabel")
        self.testTimeLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.testTimeLabel.setGeometry(QtCore.QRect(380, 30, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLabel.sizePolicy().hasHeightForWidth())
        self.testTimeLabel.setSizePolicy(sizePolicy)
        self.testTimeLabel.setMaximumSize(QtCore.QSize(150, 20))
        self.testTimeLabel.setObjectName("testTimeLabel")
        self.testTittleLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.testTittleLabel.setGeometry(QtCore.QRect(300, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTittleLabel.sizePolicy().hasHeightForWidth())
        self.testTittleLabel.setSizePolicy(sizePolicy)
        self.testTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testTittleLabel.setFont(font)
        self.testTittleLabel.setObjectName("testTittleLabel")
        self.notesTittleLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.notesTittleLabel.setGeometry(QtCore.QRect(300, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTittleLabel.sizePolicy().hasHeightForWidth())
        self.notesTittleLabel.setSizePolicy(sizePolicy)
        self.notesTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notesTittleLabel.setFont(font)
        self.notesTittleLabel.setObjectName("notesTittleLabel")
        self.resultTittleLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.resultTittleLabel.setGeometry(QtCore.QRect(300, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTittleLabel.sizePolicy().hasHeightForWidth())
        self.resultTittleLabel.setSizePolicy(sizePolicy)
        self.resultTittleLabel.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTittleLabel.setFont(font)
        self.resultTittleLabel.setObjectName("resultTittleLabel")
        self.notesLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.notesLabel.setGeometry(QtCore.QRect(380, 70, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel.sizePolicy().hasHeightForWidth())
        self.notesLabel.setSizePolicy(sizePolicy)
        self.notesLabel.setMaximumSize(QtCore.QSize(150, 20))
        self.notesLabel.setObjectName("notesLabel")
        self.iconLabel = QtWidgets.QLabel(self.monitorGroupBox)
        self.iconLabel.setGeometry(QtCore.QRect(600, 30, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel.sizePolicy().hasHeightForWidth())
        self.iconLabel.setSizePolicy(sizePolicy)
        self.iconLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.iconLabel.setAutoFillBackground(False)
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout.addWidget(self.monitorGroupBox)
        self.monitorGroupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.monitorGroupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox_2.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox_2.setSizePolicy(sizePolicy)
        self.monitorGroupBox_2.setMinimumSize(QtCore.QSize(680, 100))
        self.monitorGroupBox_2.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitorGroupBox_2.setFont(font)
        self.monitorGroupBox_2.setObjectName("monitorGroupBox_2")
        self.typeLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.typeLabel_2.setGeometry(QtCore.QRect(100, 30, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel_2.sizePolicy().hasHeightForWidth())
        self.typeLabel_2.setSizePolicy(sizePolicy)
        self.typeLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        self.typeLabel_2.setObjectName("typeLabel_2")
        self.intervalLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.intervalLabel_2.setGeometry(QtCore.QRect(100, 50, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel_2.sizePolicy().hasHeightForWidth())
        self.intervalLabel_2.setSizePolicy(sizePolicy)
        self.intervalLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        self.intervalLabel_2.setObjectName("intervalLabel_2")
        self.urlLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.urlLabel_2.setGeometry(QtCore.QRect(100, 70, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel_2.sizePolicy().hasHeightForWidth())
        self.urlLabel_2.setSizePolicy(sizePolicy)
        self.urlLabel_2.setMaximumSize(QtCore.QSize(200, 20))
        self.urlLabel_2.setObjectName("urlLabel_2")
        self.typeTittleLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.typeTittleLabel_2.setGeometry(QtCore.QRect(20, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeTittleLabel_2.sizePolicy().hasHeightForWidth())
        self.typeTittleLabel_2.setSizePolicy(sizePolicy)
        self.typeTittleLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeTittleLabel_2.setFont(font)
        self.typeTittleLabel_2.setObjectName("typeTittleLabel_2")
        self.intervalTittleLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.intervalTittleLabel_2.setGeometry(QtCore.QRect(20, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalTittleLabel_2.sizePolicy().hasHeightForWidth())
        self.intervalTittleLabel_2.setSizePolicy(sizePolicy)
        self.intervalTittleLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.intervalTittleLabel_2.setFont(font)
        self.intervalTittleLabel_2.setObjectName("intervalTittleLabel_2")
        self.urlTittleLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.urlTittleLabel_2.setGeometry(QtCore.QRect(20, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlTittleLabel_2.sizePolicy().hasHeightForWidth())
        self.urlTittleLabel_2.setSizePolicy(sizePolicy)
        self.urlTittleLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urlTittleLabel_2.setFont(font)
        self.urlTittleLabel_2.setObjectName("urlTittleLabel_2")
        self.resultLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.resultLabel_2.setGeometry(QtCore.QRect(380, 50, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultLabel_2.sizePolicy().hasHeightForWidth())
        self.resultLabel_2.setSizePolicy(sizePolicy)
        self.resultLabel_2.setMaximumSize(QtCore.QSize(150, 20))
        self.resultLabel_2.setObjectName("resultLabel_2")
        self.testTimeLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.testTimeLabel_2.setGeometry(QtCore.QRect(380, 30, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLabel_2.sizePolicy().hasHeightForWidth())
        self.testTimeLabel_2.setSizePolicy(sizePolicy)
        self.testTimeLabel_2.setMaximumSize(QtCore.QSize(150, 20))
        self.testTimeLabel_2.setObjectName("testTimeLabel_2")
        self.testTittleLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.testTittleLabel_2.setGeometry(QtCore.QRect(300, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTittleLabel_2.sizePolicy().hasHeightForWidth())
        self.testTittleLabel_2.setSizePolicy(sizePolicy)
        self.testTittleLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testTittleLabel_2.setFont(font)
        self.testTittleLabel_2.setObjectName("testTittleLabel_2")
        self.notesTittleLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.notesTittleLabel_2.setGeometry(QtCore.QRect(300, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTittleLabel_2.sizePolicy().hasHeightForWidth())
        self.notesTittleLabel_2.setSizePolicy(sizePolicy)
        self.notesTittleLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notesTittleLabel_2.setFont(font)
        self.notesTittleLabel_2.setObjectName("notesTittleLabel_2")
        self.resultTittleLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.resultTittleLabel_2.setGeometry(QtCore.QRect(300, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTittleLabel_2.sizePolicy().hasHeightForWidth())
        self.resultTittleLabel_2.setSizePolicy(sizePolicy)
        self.resultTittleLabel_2.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTittleLabel_2.setFont(font)
        self.resultTittleLabel_2.setObjectName("resultTittleLabel_2")
        self.notesLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.notesLabel_2.setGeometry(QtCore.QRect(380, 70, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel_2.sizePolicy().hasHeightForWidth())
        self.notesLabel_2.setSizePolicy(sizePolicy)
        self.notesLabel_2.setMaximumSize(QtCore.QSize(150, 20))
        self.notesLabel_2.setObjectName("notesLabel_2")
        self.iconLabel_2 = QtWidgets.QLabel(self.monitorGroupBox_2)
        self.iconLabel_2.setGeometry(QtCore.QRect(600, 30, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel_2.sizePolicy().hasHeightForWidth())
        self.iconLabel_2.setSizePolicy(sizePolicy)
        self.iconLabel_2.setMaximumSize(QtCore.QSize(60, 60))
        self.iconLabel_2.setAutoFillBackground(False)
        self.iconLabel_2.setText("")
        self.iconLabel_2.setObjectName("iconLabel_2")
        self.verticalLayout.addWidget(self.monitorGroupBox_2)


        self.monitorGroupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.monitorGroupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox_3.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox_3.setSizePolicy(sizePolicy)
        self.monitorGroupBox_3.setMinimumSize(QtCore.QSize(680, 100))
        self.monitorGroupBox_3.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitorGroupBox_3.setFont(font)
        self.monitorGroupBox_3.setObjectName("monitorGroupBox_3")
        self.typeLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.typeLabel_3.setGeometry(QtCore.QRect(100, 30, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel_3.sizePolicy().hasHeightForWidth())
        self.typeLabel_3.setSizePolicy(sizePolicy)
        self.typeLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        self.typeLabel_3.setObjectName("typeLabel_3")
        self.intervalLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.intervalLabel_3.setGeometry(QtCore.QRect(100, 50, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel_3.sizePolicy().hasHeightForWidth())
        self.intervalLabel_3.setSizePolicy(sizePolicy)
        self.intervalLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        self.intervalLabel_3.setObjectName("intervalLabel_3")
        self.urlLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.urlLabel_3.setGeometry(QtCore.QRect(100, 70, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel_3.sizePolicy().hasHeightForWidth())
        self.urlLabel_3.setSizePolicy(sizePolicy)
        self.urlLabel_3.setMaximumSize(QtCore.QSize(200, 20))
        self.urlLabel_3.setObjectName("urlLabel_3")
        self.typeTittleLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.typeTittleLabel_3.setGeometry(QtCore.QRect(20, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeTittleLabel_3.sizePolicy().hasHeightForWidth())
        self.typeTittleLabel_3.setSizePolicy(sizePolicy)
        self.typeTittleLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeTittleLabel_3.setFont(font)
        self.typeTittleLabel_3.setObjectName("typeTittleLabel_3")
        self.intervalTittleLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.intervalTittleLabel_3.setGeometry(QtCore.QRect(20, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalTittleLabel_3.sizePolicy().hasHeightForWidth())
        self.intervalTittleLabel_3.setSizePolicy(sizePolicy)
        self.intervalTittleLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.intervalTittleLabel_3.setFont(font)
        self.intervalTittleLabel_3.setObjectName("intervalTittleLabel_3")
        self.urlTittleLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.urlTittleLabel_3.setGeometry(QtCore.QRect(20, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlTittleLabel_3.sizePolicy().hasHeightForWidth())
        self.urlTittleLabel_3.setSizePolicy(sizePolicy)
        self.urlTittleLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urlTittleLabel_3.setFont(font)
        self.urlTittleLabel_3.setObjectName("urlTittleLabel_3")
        self.resultLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.resultLabel_3.setGeometry(QtCore.QRect(380, 50, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultLabel_3.sizePolicy().hasHeightForWidth())
        self.resultLabel_3.setSizePolicy(sizePolicy)
        self.resultLabel_3.setMaximumSize(QtCore.QSize(150, 20))
        self.resultLabel_3.setObjectName("resultLabel_3")
        self.testTimeLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.testTimeLabel_3.setGeometry(QtCore.QRect(380, 30, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLabel_3.sizePolicy().hasHeightForWidth())
        self.testTimeLabel_3.setSizePolicy(sizePolicy)
        self.testTimeLabel_3.setMaximumSize(QtCore.QSize(150, 20))
        self.testTimeLabel_3.setObjectName("testTimeLabel_3")
        self.testTittleLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.testTittleLabel_3.setGeometry(QtCore.QRect(300, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTittleLabel_3.sizePolicy().hasHeightForWidth())
        self.testTittleLabel_3.setSizePolicy(sizePolicy)
        self.testTittleLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testTittleLabel_3.setFont(font)
        self.testTittleLabel_3.setObjectName("testTittleLabel_3")
        self.notesTittleLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.notesTittleLabel_3.setGeometry(QtCore.QRect(300, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTittleLabel_3.sizePolicy().hasHeightForWidth())
        self.notesTittleLabel_3.setSizePolicy(sizePolicy)
        self.notesTittleLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notesTittleLabel_3.setFont(font)
        self.notesTittleLabel_3.setObjectName("notesTittleLabel_3")
        self.resultTittleLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.resultTittleLabel_3.setGeometry(QtCore.QRect(300, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTittleLabel_3.sizePolicy().hasHeightForWidth())
        self.resultTittleLabel_3.setSizePolicy(sizePolicy)
        self.resultTittleLabel_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTittleLabel_3.setFont(font)
        self.resultTittleLabel_3.setObjectName("resultTittleLabel_3")
        self.notesLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.notesLabel_3.setGeometry(QtCore.QRect(380, 70, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel_3.sizePolicy().hasHeightForWidth())
        self.notesLabel_3.setSizePolicy(sizePolicy)
        self.notesLabel_3.setMaximumSize(QtCore.QSize(150, 20))
        self.notesLabel_3.setObjectName("notesLabel_3")
        self.iconLabel_3 = QtWidgets.QLabel(self.monitorGroupBox_3)
        self.iconLabel_3.setGeometry(QtCore.QRect(600, 30, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel_3.sizePolicy().hasHeightForWidth())
        self.iconLabel_3.setSizePolicy(sizePolicy)
        self.iconLabel_3.setMaximumSize(QtCore.QSize(60, 60))
        self.iconLabel_3.setAutoFillBackground(False)
        self.iconLabel_3.setText("")
        self.iconLabel_3.setObjectName("iconLabel_3")
        self.verticalLayout.addWidget(self.monitorGroupBox_3)


        self.monitorGroupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.monitorGroupBox_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox_4.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox_4.setSizePolicy(sizePolicy)
        self.monitorGroupBox_4.setMinimumSize(QtCore.QSize(680, 100))
        self.monitorGroupBox_4.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitorGroupBox_4.setFont(font)
        self.monitorGroupBox_4.setObjectName("monitorGroupBox_4")
        self.typeLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.typeLabel_4.setGeometry(QtCore.QRect(100, 30, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel_4.sizePolicy().hasHeightForWidth())
        self.typeLabel_4.setSizePolicy(sizePolicy)
        self.typeLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        self.typeLabel_4.setObjectName("typeLabel_4")
        self.intervalLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.intervalLabel_4.setGeometry(QtCore.QRect(100, 50, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel_4.sizePolicy().hasHeightForWidth())
        self.intervalLabel_4.setSizePolicy(sizePolicy)
        self.intervalLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        self.intervalLabel_4.setObjectName("intervalLabel_4")
        self.urlLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.urlLabel_4.setGeometry(QtCore.QRect(100, 70, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel_4.sizePolicy().hasHeightForWidth())
        self.urlLabel_4.setSizePolicy(sizePolicy)
        self.urlLabel_4.setMaximumSize(QtCore.QSize(200, 20))
        self.urlLabel_4.setObjectName("urlLabel_4")
        self.typeTittleLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.typeTittleLabel_4.setGeometry(QtCore.QRect(20, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeTittleLabel_4.sizePolicy().hasHeightForWidth())
        self.typeTittleLabel_4.setSizePolicy(sizePolicy)
        self.typeTittleLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeTittleLabel_4.setFont(font)
        self.typeTittleLabel_4.setObjectName("typeTittleLabel_4")
        self.intervalTittleLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.intervalTittleLabel_4.setGeometry(QtCore.QRect(20, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalTittleLabel_4.sizePolicy().hasHeightForWidth())
        self.intervalTittleLabel_4.setSizePolicy(sizePolicy)
        self.intervalTittleLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.intervalTittleLabel_4.setFont(font)
        self.intervalTittleLabel_4.setObjectName("intervalTittleLabel_4")
        self.urlTittleLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.urlTittleLabel_4.setGeometry(QtCore.QRect(20, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlTittleLabel_4.sizePolicy().hasHeightForWidth())
        self.urlTittleLabel_4.setSizePolicy(sizePolicy)
        self.urlTittleLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urlTittleLabel_4.setFont(font)
        self.urlTittleLabel_4.setObjectName("urlTittleLabel_4")
        self.resultLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.resultLabel_4.setGeometry(QtCore.QRect(380, 50, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultLabel_4.sizePolicy().hasHeightForWidth())
        self.resultLabel_4.setSizePolicy(sizePolicy)
        self.resultLabel_4.setMaximumSize(QtCore.QSize(150, 20))
        self.resultLabel_4.setObjectName("resultLabel_4")
        self.testTimeLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.testTimeLabel_4.setGeometry(QtCore.QRect(380, 30, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLabel_4.sizePolicy().hasHeightForWidth())
        self.testTimeLabel_4.setSizePolicy(sizePolicy)
        self.testTimeLabel_4.setMaximumSize(QtCore.QSize(150, 20))
        self.testTimeLabel_4.setObjectName("testTimeLabel_4")
        self.testTittleLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.testTittleLabel_4.setGeometry(QtCore.QRect(300, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTittleLabel_4.sizePolicy().hasHeightForWidth())
        self.testTittleLabel_4.setSizePolicy(sizePolicy)
        self.testTittleLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testTittleLabel_4.setFont(font)
        self.testTittleLabel_4.setObjectName("testTittleLabel_4")
        self.notesTittleLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.notesTittleLabel_4.setGeometry(QtCore.QRect(300, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTittleLabel_4.sizePolicy().hasHeightForWidth())
        self.notesTittleLabel_4.setSizePolicy(sizePolicy)
        self.notesTittleLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notesTittleLabel_4.setFont(font)
        self.notesTittleLabel_4.setObjectName("notesTittleLabel_4")
        self.resultTittleLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.resultTittleLabel_4.setGeometry(QtCore.QRect(300, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTittleLabel_4.sizePolicy().hasHeightForWidth())
        self.resultTittleLabel_4.setSizePolicy(sizePolicy)
        self.resultTittleLabel_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTittleLabel_4.setFont(font)
        self.resultTittleLabel_4.setObjectName("resultTittleLabel_4")
        self.notesLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.notesLabel_4.setGeometry(QtCore.QRect(380, 70, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel_4.sizePolicy().hasHeightForWidth())
        self.notesLabel_4.setSizePolicy(sizePolicy)
        self.notesLabel_4.setMaximumSize(QtCore.QSize(150, 20))
        self.notesLabel_4.setObjectName("notesLabel_4")
        self.iconLabel_4 = QtWidgets.QLabel(self.monitorGroupBox_4)
        self.iconLabel_4.setGeometry(QtCore.QRect(600, 30, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel_4.sizePolicy().hasHeightForWidth())
        self.iconLabel_4.setSizePolicy(sizePolicy)
        self.iconLabel_4.setMaximumSize(QtCore.QSize(60, 60))
        self.iconLabel_4.setAutoFillBackground(False)
        self.iconLabel_4.setText("")
        self.iconLabel_4.setObjectName("iconLabel_4")
        self.verticalLayout.addWidget(self.monitorGroupBox_4)
        self.monitorGroupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.monitorGroupBox_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox_5.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox_5.setSizePolicy(sizePolicy)
        self.monitorGroupBox_5.setMinimumSize(QtCore.QSize(680, 100))
        self.monitorGroupBox_5.setMaximumSize(QtCore.QSize(680, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitorGroupBox_5.setFont(font)
        self.monitorGroupBox_5.setObjectName("monitorGroupBox_5")
        self.typeLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.typeLabel_5.setGeometry(QtCore.QRect(100, 30, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel_5.sizePolicy().hasHeightForWidth())
        self.typeLabel_5.setSizePolicy(sizePolicy)
        self.typeLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        self.typeLabel_5.setObjectName("typeLabel_5")
        self.intervalLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.intervalLabel_5.setGeometry(QtCore.QRect(100, 50, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel_5.sizePolicy().hasHeightForWidth())
        self.intervalLabel_5.setSizePolicy(sizePolicy)
        self.intervalLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        self.intervalLabel_5.setObjectName("intervalLabel_5")
        self.urlLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.urlLabel_5.setGeometry(QtCore.QRect(100, 70, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel_5.sizePolicy().hasHeightForWidth())
        self.urlLabel_5.setSizePolicy(sizePolicy)
        self.urlLabel_5.setMaximumSize(QtCore.QSize(200, 20))
        self.urlLabel_5.setObjectName("urlLabel_5")
        self.typeTittleLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.typeTittleLabel_5.setGeometry(QtCore.QRect(20, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeTittleLabel_5.sizePolicy().hasHeightForWidth())
        self.typeTittleLabel_5.setSizePolicy(sizePolicy)
        self.typeTittleLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.typeTittleLabel_5.setFont(font)
        self.typeTittleLabel_5.setObjectName("typeTittleLabel_5")
        self.intervalTittleLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.intervalTittleLabel_5.setGeometry(QtCore.QRect(20, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalTittleLabel_5.sizePolicy().hasHeightForWidth())
        self.intervalTittleLabel_5.setSizePolicy(sizePolicy)
        self.intervalTittleLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.intervalTittleLabel_5.setFont(font)
        self.intervalTittleLabel_5.setObjectName("intervalTittleLabel_5")
        self.urlTittleLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.urlTittleLabel_5.setGeometry(QtCore.QRect(20, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlTittleLabel_5.sizePolicy().hasHeightForWidth())
        self.urlTittleLabel_5.setSizePolicy(sizePolicy)
        self.urlTittleLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urlTittleLabel_5.setFont(font)
        self.urlTittleLabel_5.setObjectName("urlTittleLabel_5")
        self.resultLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.resultLabel_5.setGeometry(QtCore.QRect(380, 50, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultLabel_5.sizePolicy().hasHeightForWidth())
        self.resultLabel_5.setSizePolicy(sizePolicy)
        self.resultLabel_5.setMaximumSize(QtCore.QSize(150, 20))
        self.resultLabel_5.setObjectName("resultLabel_5")
        self.testTimeLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.testTimeLabel_5.setGeometry(QtCore.QRect(380, 30, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLabel_5.sizePolicy().hasHeightForWidth())
        self.testTimeLabel_5.setSizePolicy(sizePolicy)
        self.testTimeLabel_5.setMaximumSize(QtCore.QSize(150, 20))
        self.testTimeLabel_5.setObjectName("testTimeLabel_5")
        self.testTittleLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.testTittleLabel_5.setGeometry(QtCore.QRect(300, 30, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTittleLabel_5.sizePolicy().hasHeightForWidth())
        self.testTittleLabel_5.setSizePolicy(sizePolicy)
        self.testTittleLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.testTittleLabel_5.setFont(font)
        self.testTittleLabel_5.setObjectName("testTittleLabel_5")
        self.notesTittleLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.notesTittleLabel_5.setGeometry(QtCore.QRect(300, 70, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTittleLabel_5.sizePolicy().hasHeightForWidth())
        self.notesTittleLabel_5.setSizePolicy(sizePolicy)
        self.notesTittleLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.notesTittleLabel_5.setFont(font)
        self.notesTittleLabel_5.setObjectName("notesTittleLabel_5")
        self.resultTittleLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.resultTittleLabel_5.setGeometry(QtCore.QRect(300, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTittleLabel_5.sizePolicy().hasHeightForWidth())
        self.resultTittleLabel_5.setSizePolicy(sizePolicy)
        self.resultTittleLabel_5.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTittleLabel_5.setFont(font)
        self.resultTittleLabel_5.setObjectName("resultTittleLabel_5")
        self.notesLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.notesLabel_5.setGeometry(QtCore.QRect(380, 70, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel_5.sizePolicy().hasHeightForWidth())
        self.notesLabel_5.setSizePolicy(sizePolicy)
        self.notesLabel_5.setMaximumSize(QtCore.QSize(150, 20))
        self.notesLabel_5.setObjectName("notesLabel_5")
        self.iconLabel_5 = QtWidgets.QLabel(self.monitorGroupBox_5)
        self.iconLabel_5.setGeometry(QtCore.QRect(600, 30, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel_5.sizePolicy().hasHeightForWidth())
        self.iconLabel_5.setSizePolicy(sizePolicy)
        self.iconLabel_5.setMaximumSize(QtCore.QSize(60, 60))
        self.iconLabel_5.setAutoFillBackground(False)
        self.iconLabel_5.setText("")
        self.iconLabel_5.setObjectName("iconLabel_5")
        self.verticalLayout.addWidget(self.monitorGroupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 120, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setMaximumSize(QtCore.QSize(720, 30))
        self.menubar.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setGeometry(QtCore.QRect(1016, 145, 120, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuFile.sizePolicy().hasHeightForWidth())
        self.menuFile.setSizePolicy(sizePolicy)
        self.menuFile.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setGeometry(QtCore.QRect(627, 351, 120, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuHelp.sizePolicy().hasHeightForWidth())
        self.menuHelp.setSizePolicy(sizePolicy)
        self.menuHelp.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTime_Zone = QtWidgets.QAction(MainWindow)
        self.actionTime_Zone.setObjectName("actionTime_Zone")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.menuEdit.addAction(self.actionTime_Zone)
        self.menuEdit.addAction(self.actionConfig)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.localTimeGroupBox.setTitle(_translate("MainWindow", "本地时间 Local Time"))
        self.localTimeLabel.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.utcTimeGroupBox.setTitle(_translate("MainWindow", "UTC 时间 UTC Time"))
        self.utcTimeLabel.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.monitorGroupBox.setTitle(_translate("MainWindow", "Monitor"))
        self.typeLabel.setText(_translate("MainWindow", "SERVER"))
        self.intervalLabel.setText(_translate("MainWindow", "5s"))
        self.urlLabel.setText(_translate("MainWindow", "www.google.com"))
        self.typeTittleLabel.setText(_translate("MainWindow", "Type:"))
        self.intervalTittleLabel.setText(_translate("MainWindow", "Interval:"))
        self.urlTittleLabel.setText(_translate("MainWindow", "URL/Host:"))
        self.resultLabel.setText(_translate("MainWindow", "SERVER"))
        self.testTimeLabel.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.testTittleLabel.setText(_translate("MainWindow", "Test Time:"))
        self.notesTittleLabel.setText(_translate("MainWindow", "Notes:"))
        self.resultTittleLabel.setText(_translate("MainWindow", "Result:"))
        self.notesLabel.setText(_translate("MainWindow", "..."))
        self.monitorGroupBox_2.setTitle(_translate("MainWindow", "Monitor"))
        self.typeLabel_2.setText(_translate("MainWindow", "SERVER"))
        self.intervalLabel_2.setText(_translate("MainWindow", "5s"))
        self.urlLabel_2.setText(_translate("MainWindow", "www.google.com"))
        self.typeTittleLabel_2.setText(_translate("MainWindow", "Type:"))
        self.intervalTittleLabel_2.setText(_translate("MainWindow", "Interval:"))
        self.urlTittleLabel_2.setText(_translate("MainWindow", "URL/Host:"))
        self.resultLabel_2.setText(_translate("MainWindow", "SERVER"))
        self.testTimeLabel_2.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.testTittleLabel_2.setText(_translate("MainWindow", "Test Time:"))
        self.notesTittleLabel_2.setText(_translate("MainWindow", "Notes:"))
        self.resultTittleLabel_2.setText(_translate("MainWindow", "Result:"))
        self.notesLabel_2.setText(_translate("MainWindow", "..."))
        self.monitorGroupBox_3.setTitle(_translate("MainWindow", "Monitor"))
        self.typeLabel_3.setText(_translate("MainWindow", "SERVER"))
        self.intervalLabel_3.setText(_translate("MainWindow", "5s"))
        self.urlLabel_3.setText(_translate("MainWindow", "www.google.com"))
        self.typeTittleLabel_3.setText(_translate("MainWindow", "Type:"))
        self.intervalTittleLabel_3.setText(_translate("MainWindow", "Interval:"))
        self.urlTittleLabel_3.setText(_translate("MainWindow", "URL/Host:"))
        self.resultLabel_3.setText(_translate("MainWindow", "SERVER"))
        self.testTimeLabel_3.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.testTittleLabel_3.setText(_translate("MainWindow", "Test Time:"))
        self.notesTittleLabel_3.setText(_translate("MainWindow", "Notes:"))
        self.resultTittleLabel_3.setText(_translate("MainWindow", "Result:"))
        self.notesLabel_3.setText(_translate("MainWindow", "..."))
        self.monitorGroupBox_4.setTitle(_translate("MainWindow", "Monitor"))
        self.typeLabel_4.setText(_translate("MainWindow", "SERVER"))
        self.intervalLabel_4.setText(_translate("MainWindow", "5s"))
        self.urlLabel_4.setText(_translate("MainWindow", "www.google.com"))
        self.typeTittleLabel_4.setText(_translate("MainWindow", "Type:"))
        self.intervalTittleLabel_4.setText(_translate("MainWindow", "Interval:"))
        self.urlTittleLabel_4.setText(_translate("MainWindow", "URL/Host:"))
        self.resultLabel_4.setText(_translate("MainWindow", "SERVER"))
        self.testTimeLabel_4.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.testTittleLabel_4.setText(_translate("MainWindow", "Test Time:"))
        self.notesTittleLabel_4.setText(_translate("MainWindow", "Notes:"))
        self.resultTittleLabel_4.setText(_translate("MainWindow", "Result:"))
        self.notesLabel_4.setText(_translate("MainWindow", "..."))
        self.monitorGroupBox_5.setTitle(_translate("MainWindow", "Monitor"))
        self.typeLabel_5.setText(_translate("MainWindow", "SERVER"))
        self.intervalLabel_5.setText(_translate("MainWindow", "5s"))
        self.urlLabel_5.setText(_translate("MainWindow", "www.google.com"))
        self.typeTittleLabel_5.setText(_translate("MainWindow", "Type:"))
        self.intervalTittleLabel_5.setText(_translate("MainWindow", "Interval:"))
        self.urlTittleLabel_5.setText(_translate("MainWindow", "URL/Host:"))
        self.resultLabel_5.setText(_translate("MainWindow", "SERVER"))
        self.testTimeLabel_5.setText(_translate("MainWindow", "2023-04-01 00:00:00"))
        self.testTittleLabel_5.setText(_translate("MainWindow", "Test Time:"))
        self.notesTittleLabel_5.setText(_translate("MainWindow", "Notes:"))
        self.resultTittleLabel_5.setText(_translate("MainWindow", "Result:"))
        self.notesLabel_5.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "+ 添加 Add"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionTime_Zone.setText(_translate("MainWindow", "Time Zone"))
        self.actionConfig.setText(_translate("MainWindow", "Settings"))

